n_repetition: 20
env_name : ant
legacy_spring : true
device : ???

configurations: 
  [
    # 1-individual tests : 
    {'n_pop' : 1,   'n_env' : 10,  'n_step': 1000 },
    {'n_pop' : 1,   'n_env' : 50,  'n_step': 200 },
    {'n_pop' : 1,   'n_env' : 625, 'n_step': 16 },
    # 10-individuals test :
    {'n_pop' : 10,  'n_env' : 5,    'n_step': 200  },
    {'n_pop' : 10,  'n_env' : 1,    'n_step': 1000  },
    # 100-indiviuals test :
    # {'n_pop' : 100, 'n_env' : 1,     'n_step': 200  }, #carefull smaller number of steps
    {'n_pop' : 100, 'n_env' : 5,     'n_step': 200  }, 
    {'n_pop' : 100, 'n_env' : 1,     'n_step': 1000  },
    # 500-pop test : 
    {'n_pop' : 500, 'n_env' : 1,     'n_step': 1000  },
  ]
save_filename : no_actor

# declaration of a methods, a list containing 
# functions wich corresponds to rollout functions to launch
classes : 
  fmm_no : no_actors.exp_utils.with_pytorch_setup
  mms_no : no_actors.exp_utils.with_jax_setup
