n_repetition: 15
legacy_spring : true
device : ???
profiling : True
env_name : walker2d
gym_version : v3
torch_device : cuda

jax_model:
  _target_ : jax_rollout.networks.flax_networks.create_MLP
  hidden_sizes : [256,256]
  activation : flax.linen.relu
    # output_activation : flax.linen.relu #  if not specified => identity activation function for the output

pytorch_model:
    _target_ : jax_rollout.networks.pytorch_networks.MLP
    hidden_sizes : [256,256]
    activation : torch.nn.ReLU
      # output_activation : #  if not specified => identity activation function for the output

n_pop : 10
n_env : 50
n_step : 200


# declaration of a methods, a list containing 
# functions wich corresponds to rollout functions to launch
method: 
  path : jax_rollout.with_actors.exp_utils.with_envpool_sync_setup
  name : pytorch_256_x2
# method: 
#   path : jax_rollout.with_actors.exp_utils.with_pytorch_setup
#   name : pytorch_256_x2
# method: 
  # path : jax_rollout.with_actors.exp_utils.with_jax_setup
  # name : jax_256_x2
# method: 
#   path : jax_rollout.no_actors.exp_utils.with_pytorch_setup
#   name : fmm_no
# method: 
#   path : jax_rollout.no_actors.exp_utils.with_pytorch_setup
#   name : mms_no
